services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=boxingrebel'
      - 'POSTGRES_DB=boxingrebel'
      - 'POSTGRES_PASSWORD=boxingrebel'
    volumes:
      - ./volumes/boxingrebel/postgres:/var/lib/postgresql/data
